name: Deploy on Dev and Main Repositories
on:
  push:
    branches:
      - dev
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Copy files via ssh
      uses: appleboy/scp-action@master
      if: github.ref == 'refs/heads/main'
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        source: docs/.
        target: ${{ secrets.SSH_DIR }}
        key: ${{ secrets.SSH_KEY }}
    - name: Copy files via ssh
      uses: appleboy/scp-action@master
      if: github.ref == 'refs/heads/dev'
      with:
        host: ${{ secrets.DEV_SSH_HOST }}
        username: ${{ secrets.DEV_SSH_USER }}
        port: ${{ secrets.DEV_SSH_PORT }}
        source: docs/.
        target: ${{ secrets.DEV_SSH_DIR }}
        key: ${{ secrets.DEV_SSH_KEY }}
